export default function personalDescription() {
    return `
        <h2 class="my-3">Este soy yo</h2>
        
                <p class="fs-5">Mi nombre es Jorge, pero en la red soy conocido como Jaip desde que tengo recuerdos. <br>Mi primer acercamiento al mundo del desarrolo fue a los 10 años con MSN Groups donde con amigos fundamos <strong class="text-warning">Los Espectros Exiliados</strong>, juego por mensajería de texto de los Caballeros del Zodiaco (lamentablemente el proyecto fue hackeado y no se puede ver mediante WayBackMachine) y más tarde me aventuré con el desarrollo web mediante <code>Microsoft FrontPage</code> pero mi limitado gusto por el buen diseño me desmotivó a seguir ese camino.</p> 
                <p class="fs-5">Un tiempo después monté un servidor de <strong class="text-warning">MU online</strong> para jugar con otras personas de internet, configurando la Base de Datos con <code>SQL Server</code> y la página Web con <code>Apache</code> para la creación de cuentas o realizar acciones de reseteo de personajes, al parecer mi destino era seguir el camino de la programación.</p>
                <p class="fs-5">Sin embargo, mi camino fue girando un poco para acercarme más y más a la <code>matemática</code>, participando en <strong class="text-warning">Olimpiadas de Matemática</strong> Regionales obteniendo dos <code>2° lugares y un 3° lugar</code>, clasificando a la Olimpiada Nacional o preseleccionado para la Cono Sur. También crecía mi interés por la <strong class="text-warning">física</strong> donde también obtuve una <code>medalla de Bronce</code> a nivel Regional en Olimpiadas. Esto acrecentaría mi interés por la Ciencia</p> 
                <p class="fs-5">Pero para nada descuidé mis otras facetas, <strong class="text-warning">ganando un concurso</strong> de <code>escritura</code> a nivel Regional con un ensayo titulado "Navengado por la Vida" o un concurso de <code>composición musical rock</code> con nuestra banda escolar <strong class="text-warning">Réplica</strong> y mi composición <i>Sin tí</i>.</p>
                <p class="fs-5">Así ingresaría a <code>Geofísica</code> en la Universidad de Concepción obteniendo <strong class="text-warning">Puntaje Máximo Nacional</strong> en la prueba de Matemática para ingresar como también el primer lugar de ingreso a la carrera. En este lugar atravesaría mis límites aprendiendo mucho y exigiéndome para poder superarme. Me interesó mucho la programación cuando cursé Computación Científica aprendiendo <code>Fortran</code>. Esto continuaría cuando aprendí <code>MatLAB</code> y otros softwares científicos ocupados en Geofísica. Nos pasábamos tardes enteras codeando y ayudando a compañeros para que sus códigos funcionaran y lograran entregar sus tareas.</p>
                <p class="fs-5">Fue en mi primer año de universidad cuando me acerqué a la <code>pedagogía</code> al participar de un preuniversitario gestionado por estudiantes de la facultad de ciencias físicas y matemáticas de la univerisdad, para más tarde el 2012 formar junto a otros compañeros de toda la universidad el <strong class="text-warning">Preuniversitario Juan Pablo Jiménez</strong> para estudiantes de todo el gran concepción, gratuito y financiado por nosotros mismos.</p>
                <p class="fs-5">Lo anterior llevó a mi cambio de carrera, quería ser profesor e ingresé a <strong class="text-warning">Pedagogía en Matemática y Computación</strong> aun a pesar de las recomendaciones de mis profesores de Geofísica quienes lamentaban mi partida. De esta manera, seguí <code>aumentando</code> mis conocimientos matemáticos universitarios y <code>profundizando</code> cada vez más en la matemática escolar.</p>
                <p class="fs-5">Por distintas razones, la pedagogía a veces es ingrata, hay un ambiente muy hostil en los lugares de trabajo y me ha tocado vivir en carne propia algunas <code>situaciones muy desesperantes</code>, por esta razón decidí ocupar todo lo aprendido para ingresar al mundo de TI a través del <strong class="text-warning">Análisis de Datos o la Ciencia de Datos</strong>.</p>
                <p class="fs-5">Pero en el camino, noté que tengo muchas habilidades que puedo ocupar para el <strong class="text-warning">desarrollo de aplicaciones</strong>, y lamentablemente, como la competencia para encontrar un trabajo es ardua, opté también por prepararme en este rubro. Si bien, <i>quién mucho abarca poco aprieta</i>, estoy seguro que mi <code>insistencia y dedicación</code> me darán frutos para poder lograr mi nuevo objetivo.</p>
                <p class="fs-5">Has llegado hasta aquí, <code>muchas gracias</code>.</p>
                </p>
            
    `
}